"""Export engagement / chat reports as Markdown."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from app.workspace import get_chat, get_engagement, list_memories, list_messages


def export_chat_markdown(user_id: str, chat_id: str) -> str:
    chat = get_chat(user_id, chat_id)
    if not chat:
        raise ValueError("Chat not found")
    messages = list_messages(user_id, chat_id)
    eng = None
    if chat.get("engagement_id"):
        eng = get_engagement(user_id, chat["engagement_id"])

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# SecuraIQ Report — {chat.get('title', 'Chat')}",
        "",
        f"- Exported: `{ts}`",
        f"- Mode: `{chat.get('mode')}`",
        f"- Chat ID: `{chat_id}`",
    ]
    if eng:
        lines += [
            f"- Engagement: **{eng['name']}** (`{eng['id']}`)",
            f"- Scope: {eng.get('scope_notes') or '_none_'}",
        ]
        mems = list_memories(user_id, eng["id"])
        if mems:
            lines += ["", "## Engagement memory", ""]
            for m in mems:
                lines.append(f"- **{m['key']}**: {m['value']}")

    lines += ["", "## Conversation", ""]
    for m in messages:
        role = m["role"].upper()
        lines.append(f"### {role}")
        lines.append("")
        lines.append(m["content"])
        lines.append("")

    lines += [
        "---",
        "_Generated by SecuraIQ for authorized security work. Include detection & remediation before delivery._",
    ]
    return "\n".join(lines)


def export_engagement_summary(user_id: str, engagement_id: str) -> dict[str, Any]:
    eng = get_engagement(user_id, engagement_id)
    if not eng:
        raise ValueError("Engagement not found")
    mems = list_memories(user_id, engagement_id)
    return {
        "engagement": eng,
        "memories": mems,
        "markdown": (
            f"# Engagement: {eng['name']}\n\n"
            f"## Scope\n{eng.get('scope_notes') or '_none_'}\n\n"
            "## Memory\n"
            + ("\n".join(f"- **{m['key']}**: {m['value']}" for m in mems) or "_empty_")
        ),
    }
